# Dev overrides for enemy location prediction
# This config extends the train/enemy_location_prediction.yaml with development-specific settings

data:
  batch_size: 8
  num_workers: 0
  task_form: "regression"  # "regression" for XYZ coords or "classification" for place labels or "generative" for CVAE
  text_processor_model: google/siglip-base-patch16-224

model:
  hidden_dim: 64
  vae:
    latent_dim: 32
    kl_weight: 1.0
  encoder:
    video:
      # from_pretrained: openai/clip-vit-base-patch32
      from_pretrained: facebook/vjepa2-vitl-fpc16-256-ssv2

training:
  max_epochs: 2
  accumulate_grad_batches: 1
  log_every_n_steps: 2
  limit_train_batches: 5 # 1.0 means use all data
  limit_val_batches: 5
  limit_test_batches: 20

wandb:
  enabled: false

checkpoint:
  step:
    every_n_train_steps: 3
