# Dev overrides for enemy location prediction
# This config extends the train/enemy_location_prediction.yaml with development-specific settings

data:
  batch_size: 8
  num_workers: 0
  task_form: multi-label-cls  # "regression" for XYZ coords or "classification" for place labels or "coord-gen" for CVAE
  num_pov_agents: 2

model:
  encoder:
    video:
      model_type: dinov2  # Options: clip, dinov2, siglip, vivit, videomae, vjepa2
  contrastive:
    enable: true

training:
  max_epochs: 2
  accumulate_grad_batches: 1
  log_every_n_steps: 2
  limit_train_batches: 4 # 1.0 means use all data
  limit_val_batches: 2
  limit_test_batches: 20

wandb:
  enabled: true

checkpoint:
  step:
    every_n_train_steps: 3
