data:
  batch_size: 1
  num_workers: 0
  task_form: traj-gen  # "regression" for XYZ coords or "classification" for place labels or "coord-gen" for CVAE

model:
  encoder:
    video:
      model_type: dinov2  # Options: clip, dinov2, siglip, vivit, videomae, vjepa2
  contrastive:
    enable: true
    
training:
  max_epochs: 2
  accumulate_grad_batches: 1
  log_every_n_steps: 2
  limit_train_batches: 2 # 1.0 means use all data
  limit_val_batches: 5
  limit_test_batches: 8

wandb:
  enabled: false
