meta:
  task: enemy_location_forecast
  fast_dev_run: false
  resume_exp: null
  exp_name: enemy-forecast
  run_name: enemy-forecast-clip

data:
  labels_filename: enemy_location_forecast_s1s_l5s_f10s.csv  # CSV with enemy future locations
  task_form: multi-label-cls # multi-label-cls, multi-output-reg, grid-cls, density-cls, coord-reg, coord-gen

wandb:
  group: '${meta.exp_name}'
  tags: ['${meta.exp_name}']
  notes: 'enemy location forecast - predict future enemy positions'

