meta:
  fast_dev_run: false
  resume_exp: null
  exp_name: self-future-location-pred
  run_name: self-future-location-pred-clip

data:
  labels_filename: teammate_location_forecast_s1s_l5s_f10s.csv  # CSV with future location predictions
  batch_size: 8
  num_workers: 9
  task_form: multi-label-cls # multi-label-cls, multi-output-reg, grid-cls, density-cls, coord-reg, coord-gen
  grid_resolution: 10  # Grid resolution (10x10 = 100 cells)
  gaussian_sigma: 1.0  # Gaussian smoothing sigma for density-cls

model:
  class_weights: null  # Options: null, inverse, inverse_sqrt, effective_num, pos_weight

wandb:
  group: '${meta.exp_name}'
  tags: ['${meta.exp_name}']
  notes: 'teammate location forecast'
